version: '3'
services:
  db:
    image: mdillon/postgis:9.6-alpine
    container_name: db_test_simetrik
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simetrik_db_external
    volumes:
      - ./seed/init_db.sql:/docker-entrypoint-initdb.d/init.sql

  minio:
    image: minio/minio
    container_name: minio_test_simetrik
    volumes:
      - ./simetrik:/data
    ports:
      - 9000:9000
    environment:
      - MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
      - MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: minio server /data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    depends_on:
      - db

  web:
    build: .
    container_name: server_test_simetrik
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/test_simetrik
    environment:
      - MINIO_HOST=minio
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=simetrik_db_external
      - DB_EXTERNAL=postgresql://postgres:postgres@db:5432/simetrik_db_external
    depends_on:
      - minio
